Add mime-type image/avif and image/avifs
h5bp/server-configs-apache pull request #251
Opened 2020-11-03 16:25 UTC by gsouquet

re: #220 

Looking at the page on [CORS enabled images](https://wiki.developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image) on MDN I realised that h5bp did not mention AVIF images at all. I have seen that an issue was opened and decided to open a PR to add both mime types

* `.avif`  => `image/avif`
* `.avifs` => `image/avif-sequence`

I followed the same default as the WEBP format, and I believe this covers most of it

Keen to hear your feedback on this

2020-11-03 16:45 UTC, LeoColomb requested changes
Thanks a lot for this PR @gsouquet 

Please see my few remarks.

2020-11-03 16:45 UTC, LeoColomb commented on dist/.htaccess
Please don't edit `.htaccess`

2020-11-03 16:45 UTC, LeoColomb commented on h5bp/cross-origin/images.conf
> +        <FilesMatch "\.(bmp|cur|gif|ico|jpe?g|a?png|svgz?|webp|avifs?)$">
👍 but better to keep alphabetic ordering, so probably at the first place in the array

```suggestion
        <FilesMatch "\.(avifs?|bmp|cur|gif|ico|jpe?g|a?png|svgz?|webp)$">
```

2020-11-03 16:45 UTC, LeoColomb commented on h5bp/web_performance/filename-based_cache_busting.conf
> +    RewriteRule ^(.+)\.(\w+)\.(bmp|css|cur|gif|ico|jpe?g|m?js|a?png|svgz?|webp|avifs?|webmanifest)$ $1.$3 [L]
👍 but better to keep alphabetic ordering, so probably at the first place in the array

```suggestion
    RewriteRule ^(.+)\.(\w+)\.(avifs?|bmp|css|cur|gif|ico|jpe?g|m?js|a?png|svgz?|webp|webmanifest)$ $1.$3 [L]
```

2020-11-03 16:45 UTC, LeoColomb commented on h5bp/media_types/media_types.conf
> +    AddType image/avif-sequence                         avifs
👍 but better to keep alphabetic ordering, so probably as first image type

2020-11-03 16:45 UTC, LeoColomb commented on h5bp/web_performance/cache_expiration.conf
> +    ExpiresByType image/avif-sequence                   "access plus 1 month"
👍 but better to keep alphabetic ordering, so probably as first image type

2020-11-03 16:53 UTC, gsouquet commented
Thank you for the quick review @LeoColomb 👍 

I hadn't notice the alphabetical ordering. This is now fixed
Also reverted `dist/.htaccess` as it seems that it is handled by `.github/workflows/release.yml`

2020-11-03 16:55 UTC, LeoColomb approved these changes
Thanks again, much better 😃

2020-11-17 22:12 UTC, XhmikosR approved these changes

2020-11-17 22:16 UTC, merged